# Generated by Django 6.0.1 on 2026-01-22 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True)),
                ('profile_url', models.URLField(blank=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('authored_at', models.DateTimeField()),
                ('committer_name', models.CharField(max_length=255)),
                ('committer_email', models.EmailField(blank=True, max_length=254)),
                ('committed_at', models.DateTimeField()),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('files_changed', models.IntegerField(default=0)),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits', to='github_app.collaborator')),
            ],
            options={
                'ordering': ['-authored_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1024)),
                ('language', models.CharField(max_length=50)),
                ('nloc', models.IntegerField(default=0)),
                ('ccn', models.IntegerField(default=0)),
                ('token_count', models.IntegerField(default=0)),
                ('function_count', models.IntegerField(default=0)),
                ('cognitive_complexity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_analyses', to='github_app.commit')),
            ],
            options={
                'verbose_name_plural': 'File analyses',
                'ordering': ['-ccn'],
            },
        ),
        migrations.CreateModel(
            name='FunctionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=512)),
                ('long_name', models.CharField(max_length=1024)),
                ('start_line', models.IntegerField()),
                ('end_line', models.IntegerField()),
                ('nloc', models.IntegerField(default=0)),
                ('ccn', models.IntegerField(default=0)),
                ('token_count', models.IntegerField(default=0)),
                ('parameter_count', models.IntegerField(default=0)),
                ('file_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='github_app.fileanalysis')),
            ],
            options={
                'verbose_name_plural': 'Function analyses',
                'ordering': ['-ccn'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_issue_id', models.BigIntegerField(unique=True)),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=512)),
                ('body', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=20)),
                ('creator_username', models.CharField(max_length=255)),
                ('labels', models.JSONField(default=list)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to='github_app.collaborator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_pr_id', models.BigIntegerField()),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=512)),
                ('body', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('merged', 'Merged')], max_length=20)),
                ('is_merged', models.BooleanField(default=False)),
                ('creator_username', models.CharField(max_length=255)),
                ('head_ref', models.CharField(max_length=255)),
                ('base_ref', models.CharField(max_length=255)),
                ('head_sha', models.CharField(max_length=40)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('changed_files', models.IntegerField(default=0)),
                ('commits_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('review_comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prs', to='github_app.collaborator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_comment_id', models.BigIntegerField(unique=True)),
                ('body', models.TextField()),
                ('author_username', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='github_app.collaborator')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='github_app.issue')),
                ('pull_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='github_app.pullrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_review_id', models.BigIntegerField(unique=True)),
                ('state', models.CharField(choices=[('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes Requested'), ('COMMENTED', 'Commented'), ('DISMISSED', 'Dismissed'), ('PENDING', 'Pending')], max_length=30)),
                ('body', models.TextField(blank=True)),
                ('reviewer_username', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField()),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='github_app.collaborator')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='github_app.pullrequest')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=512)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('fetch_status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('fetch_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'full_name')},
            },
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='github_app.repository'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('activity_gap', 'Activity Gap'), ('no_commits', 'No Commits'), ('no_reviews', 'No Reviews')], max_length=30)),
                ('message', models.TextField()),
                ('gap_days', models.IntegerField(default=0)),
                ('gap_start', models.DateTimeField(blank=True, null=True)),
                ('gap_end', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='github_app.collaborator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_notifications', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='github_app.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='github_app.repository'),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_analyses', to='github_app.repository'),
        ),
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='github_app.repository'),
        ),
        migrations.CreateModel(
            name='CloneTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField()),
                ('temp_path', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('cloning', 'Cloning'), ('extracting', 'Extracting'), ('analyzing', 'Analyzing'), ('pending_cleanup', 'Pending Cleanup'), ('cleaned', 'Cleaned'), ('failed', 'Failed')], default='cloning', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clone_trackers', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clone_trackers', to='github_app.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sha', models.CharField(max_length=40)),
                ('is_default', models.BooleanField(default=False)),
                ('is_protected', models.BooleanField(default=False)),
                ('is_merged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='github_app.repository')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='RepositoryCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=7)),
                ('permission', models.CharField(choices=[('admin', 'Admin'), ('maintain', 'Maintain'), ('write', 'Write'), ('triage', 'Triage'), ('read', 'Read')], default='read', max_length=20)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_collaborators', to='github_app.collaborator')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_collaborators', to='github_app.repository')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pullrequest',
            constraint=models.UniqueConstraint(fields=('github_pr_id', 'repository'), name='unique_pr_per_repo'),
        ),
        migrations.AddConstraint(
            model_name='commit',
            constraint=models.UniqueConstraint(fields=('sha', 'repository'), name='unique_commit_per_repo'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('repository', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='repositorycollaborator',
            unique_together={('repository', 'collaborator')},
        ),
    ]
